### ISSUE TITLE
preempted job left pending in queue for 120 seconds

### ISSUE THREAD

**Issue by rillet** [openlava/openlava#86]
I have a question concerning the preemption feature in OpenLava 3.3.1.

It seems that a preempted job is made to wait 120 seconds (left pending in queue) before it resumes regardless of the completion of the preempting (higher-priority) job.

Question:
1. What is the reason for the "120 seconds"?
2. What problems would arise if I changed this value?

related code? ( openlava/lsbatch/daemons/mbd.main.c )
```
    jPtr->shared->jobBill.beginTime = time(NULL) + 120;
    jPtr->newReason = PEND_JOB_PREEMPTED;
```

**Comment by openlava** [comment]
This is to prevent the preempted job to start before the job that caused the
preemption. This is the current implementation in the code base you have
since the mbatchd tries first to resume suspended jobs before scheduling
the pending ones. You can decrease it if in your environment jobs are
shorter.


Thanks
David Bigagli
www.openlava.org

**Comment by rillet** [comment]
O.K. I can change it with peace of mind.
I wish you would make this a parameter in future version.

Thanks
